bytedance/flowgram.ai

apps/demo-fixed-layout/src/nodes/default-form-meta.tsx, apps/demo-fixed-layout/src/nodes/end/form-meta.tsx, apps/demo-fixed-layout/src/nodes/start/form-meta.tsx
`FormRenderProps`'s generic type should be form's data type instead of `FlowNodeJSON`
=> chore: fix demo form data type

apps/docs/src/en/guide/advanced/interactive/shortcuts.mdx, apps/docs/src/zh/guide/advanced/interactive/shortcuts.mdx
=> docs: example and code sync

apps/docs/global.less
In official website documents, there are some abnormal text colors in both bright and dark modes. This pr is to solve this problem.
=> fix: resolve tooltip text-color abnormal

apps/demo-node-form/src/components/field-wrapper.tsx, apps/demo-node-form/src/constant.ts, apps/docs/components/node-form/array/index.css, apps/docs/components/node-form/array/node-registry.tsx, apps/docs/components/node-form/array/preview.tsx, apps/docs/src/zh/examples/node-form/_meta.json, apps/docs/src/zh/examples/node-form/array.mdx, packages/node-engine/form/__tests__/field-array-model.test.ts, packages/node-engine/form/src/core/field-array-model.ts, packages/node-engine/form/src/core/utils.ts, packages/node-engine/form/src/types/form.ts, packages/node-engine/node/src/form-model-v2.ts
**1. bugfix: error state is not swapped when using `ArrayField.swap`** 
before:
after:
**2. add `get values() `method to `FormModel`**
=> fix: fix FieldArrayModel.swap state issue with doc example covered

packages/node-engine/form/__tests__/field-array-model.test.ts, packages/node-engine/form/__tests__/object.test.ts, packages/node-engine/form/src/core/path.ts, packages/node-engine/form/src/utils/object.ts
- do not delete object key when `shallowSetIn` value is `undefined`, this will cause field missing in object data structure case.
-  fix error message in `Path`
- add a unit test for chained `FieldArray.swap` case
=> fix: do not delete object key when shallowSetIn value is undefined, fix err msg and add a ut

packages/node-engine/form/__tests__/form-model.test.ts, packages/node-engine/form/__tests__/glob.test.ts, packages/node-engine/form/src/utils/glob.ts
This fix is for validate rule pattern matching when path value is multiple layer `undefiend`, for example,
if data is `{a:{}}`, validate rule on  `a.b.c` will not be executed before this fix.
=> fix: fix multiple layer undefined pattern matching

packages/canvas-engine/document/__tests__/services/flow-operation-base-service.test.ts, packages/common/history/__tests__/history-service.test.ts, packages/common/history/src/history/history-service.ts
1. If no operations are pushed when executing a transaction, no exception is thrown. 
2. Add a test for move node
=> fix: transact no operation should not throw error

packages/node-engine/form/__tests__/field-model.test.ts, packages/node-engine/form/src/core/field-model.ts, packages/node-engine/form/src/core/form-model.ts
Fix the issue that when multiple patterns match in validate config, only the first found one will be triggered, for example:
```
{
validate: {
'a.*.b': someValidateFunction
'a.x.b': anotherValidateFunction
}
}
```
=> fix: fix FormModel.validateIn only match one pattern

apps/demo-fixed-layout/src/plugins/sync-variable-plugin/variable-selector/use-variable-tree.ts, apps/demo-free-layout/src/plugins/sync-variable-plugin/variable-selector/use-variable-tree.ts, apps/docs/src/en/guide/advanced/variable.mdx, apps/docs/src/zh/guide/advanced/variable.mdx, packages/variable-engine/variable-core/__tests__/ast/variable-declaration.test.ts, packages/variable-engine/variable-core/__tests__/ast/variable-match.test.ts, packages/variable-engine/variable-core/src/ast/index.ts, packages/variable-engine/variable-core/src/ast/match.ts, packages/variable-engine/variable-core/src/ast/utils/helpers.ts
Before:
```
import {
isMatchAST,
type ObjectType,
type ArrayType,
} from '@flowgram.ai/fixed-layout-editor';
if (isMatchAST(node, ObjectType)) {
// do something
}
if (isMatchAST(node, ArrayType)) {
// do something
}
```
After:
```
import {
ASTMatch
} from '@flowgram.ai/fixed-layout-editor';
if (ASTMatch.isObject(node)) {
// do something
}
if (ASTMatch.isArray(node)) {
// do something
}
```
=> feat: add ASTMatch API in variable-core

README.md, packages/materials/form-materials/bin/index.js
When run `npx @flowgram.ai/form-materials`, it returns error:
Fix it by adding `#!/usr/bin/env node` to first line of scripts
=> fix: npx @flowgram.ai/form-materials cli

packages/materials/form-materials/src/components/json-schema-editor/index.tsx, packages/materials/form-materials/src/components/json-schema-editor/types.ts, packages/materials/form-materials/src/components/variable-selector/index.tsx
Add a config property to the VariableSelector and JsonSchemaEditor components, supporting custom placeholders, description titles, description placeholders, and add button text. This enhances the flexibility and configurability of the components, allowing them to better adapt to different use cases.
apps/demo-free-layout/src/nodes/start/form-meta.tsx
apps/demo-free-layout/src/form-components/fx-expression/index.tsx
=> feat(materials): Add config options for VariableSelector and JsonSchemaEditor

apps/demo-fixed-layout/src/nodes/default-form-meta.tsx, apps/demo-free-layout/src/nodes/default-form-meta.tsx, common/config/rush/pnpm-lock.yaml, packages/materials/form-materials/package.json, packages/materials/form-materials/src/components/json-schema-editor/components/blur-input.tsx, packages/materials/form-materials/src/components/json-schema-editor/index.tsx, packages/materials/form-materials/src/components/variable-selector/index.tsx, packages/materials/form-materials/src/effects/auto-rename-ref/config.json, packages/materials/form-materials/src/effects/auto-rename-ref/index.ts, packages/materials/form-materials/src/effects/index.ts, packages/variable-engine/variable-core/src/ast/ast-registers.ts
How to use:
```typescript
const formMeta = {
effect: {
inputsValues: autoRenameRefEffect,
},
}
```
依旧存在问题：子画布中的 Effect 会被调用 effectReturn 从而销毁监听，可以 @louisyoungx 帮忙看看
=> feat(material): auto rename effect

packages/plugins/free-container-plugin/src/sub-canvas/components/render/index.tsx, packages/plugins/free-container-plugin/src/sub-canvas/components/tips/index.tsx, packages/plugins/free-container-plugin/src/sub-canvas/components/tips/style.ts
Enhanced the `SubCanvasRender` component to support customizable tip text that accepts both strings and React elements.
- Add `tipText?: string | React.ReactNode` prop to `SubCanvasRender`
- Support custom React element rendering in tips
- Maintain 100% backward compatibility
- Add proper TypeScript types and CSS styling
```tsx
// String (backward compatible)
<SubCanvasRender tipText="Custom tip text" />
// React element (new feature)  
<SubCanvasRender tipText={<span><Icon />Custom tip</span>} />
```
- ✅ Resolved merge conflicts with latest main branch changes
- ✅ Compatible with new `offsetY` default value (`offsetY = 0`)
- ✅ Rebased on latest main branch (004b8ac8)
=> feat(free-container-plugin): support customizable tip text and React elements

apps/demo-free-layout/src/hooks/use-editor-props.tsx, apps/demo-free-layout/src/styles/index.css, apps/docs/src/en/api/components/workflow-node-renderer.mdx, apps/docs/src/en/guide/advanced/free-layout/port.mdx, apps/docs/src/zh/api/components/workflow-node-renderer.mdx, apps/docs/src/zh/guide/advanced/free-layout/port.mdx, packages/canvas-engine/free-layout-core/src/typings/workflow-line.ts, packages/client/free-layout-editor/src/components/workflow-node-renderer.tsx, packages/plugins/free-lines-plugin/src/components/workflow-port-render/index.tsx
添加端口颜色自定义功能，允许通过 props 方式自定义 WorkflowPortRender 组件的颜色，替代之前需要通过 CSS 选择器覆盖样式的方案。
之前要自定义端口颜色需要通过复杂的 CSS 选择器：
```css
div[data-port-entity-type='input'].workflow-port-render { /* 样式 */ }
div[data-port-entity-type='output'].workflow-port-render { /* 样式 */ }
```
现在可以直接通过 props 传递：
```tsx
<WorkflowNodeRenderer 
portPrimaryColor="#4d53e8" 
portSecondaryColor="#9197f1" 
/>
```
**WorkflowPortRender 组件:**
- `primaryColor?: string` - 激活状态颜色 (linked/hovered)
- `secondaryColor?: string` - 默认状态颜色
- `errorColor?: string` - 错误状态颜色
- `backgroundColor?: string` - 背景颜色
**WorkflowNodeRenderer 组件:**
- `portPrimaryColor?: string` - 端口激活状态颜色
- `portSecondaryColor?: string` - 端口默认状态颜色
- `portErrorColor?: string` - 端口错误状态颜色
- `portBackgroundColor?: string` - 端口背景颜色
- 使用 CSS 自定义属性 (CSS Variables) 覆盖默认颜色
- 运行时动态设置 …
=> feat: add customizable port colors to WorkflowPortRender

CHANGELOG.md, apps/demo-free-layout/src/hooks/use-editor-props.tsx, apps/docs/src/en/guide/advanced/free-layout/line.mdx, packages/canvas-engine/free-layout-core/__tests__/workflow-lines-manager.test.ts, packages/canvas-engine/free-layout-core/src/typings/workflow-line.ts, packages/canvas-engine/free-layout-core/src/workflow-lines-manager.ts
为 `LineColor` 接口添加 `flowing` 字段，支持配置工作流执行时的流动线条颜色，提升视觉反馈效果。
- ✅ **新增 `flowing: string` 字段** 到 LineColor 接口
- ✅ **添加 LineColors.FLOWING 枚举** 支持 CSS 变量
- ✅ **增强 getLineColor() 方法** 支持流动状态检测
- ✅ **更新示例配置和文档** 包含使用说明
- ✅ **添加完整测试覆盖** 确保功能稳定
```typescript
const editorProps: FreeLayoutProps = {
lineColor: {
// ... 其他颜色配置
flowing: '#ff6b35', // 🆕 流动线条颜色
},
isFlowingLine: (ctx, line) =>
ctx.get(WorkflowRuntimeService).isFlowingLine(line),
}
```
1. **增强用户体验** - 工作流执行时的视觉反馈
2. **CSS 变量支持** - `var(--g-workflow-line-color-flowing, #4d53e8)`
3. **智能优先级** - hidden > error > highlight > drawing > hovered > selected > **flowing** > default
4. **零破坏性更改** - 现有代码无需修改
无破坏性更改，可安全合并！🚀
=> feat(core): add flowing field to LineColor interface

packages/canvas-engine/core/src/react/playground-react-provider.tsx, packages/canvas-engine/core/src/react/playground-react-renderer.tsx
React 18 and above executes `useEffect` twice in StrictMode to prevent incorrect use of side effects.
There are two approaches to address this:
1. The more standard approach is to refactor these two code sections using React 18's new API - `useSyncExternalStore`. The trade-off is that React 16 and 17 will no longer be supported.
2. Another approach is to make `useEffect` itself idempotent, where both the creation and destruction of the playground occur within the same effect.
Considering that many developers' projects are still using React 16 or 17, we have ultimately decided to implement the second approach.
=> feat(core): make playground effect idempotent to support React.StrictMode

packages/materials/form-materials/src/components/json-schema-editor/index.tsx
add className prop to JsonSchemaEditor and adjust button styling
1.增加className配置项 2.调整“添加按钮”左边距
[
=> feat(materials): add className prop to JsonSchemaEditor

apps/demo-fixed-layout/src/form-components/form-inputs/index.tsx, apps/demo-fixed-layout/src/nodes/default-form-meta.tsx, apps/demo-free-layout/src/form-components/form-inputs/index.tsx, apps/demo-free-layout/src/nodes/default-form-meta.tsx, packages/client/editor/src/index.ts, packages/node-engine/form/src/core/field-model.ts, packages/node-engine/form/src/core/form-model.ts, packages/node-engine/form/src/index.ts, packages/node-engine/form/src/types/validate.ts
```tsx
{
validate: {
'inputsValues.*': ({ value, context, formValues, name }) => {
const valuePropetyKey = name.replace(/^inputsValues\./, '');
const required = formValues.inputs?.required || [];
if (
required.includes(valuePropetyKey) &&
(value === '' || value === undefined || value?.content === '')
) {
return {
message:  <span>{valuePropetyKey} is required </span>,
level: FeedbackLevel.Warning,
};
}
return undefined;
},
}
```
=> fix(form): validate return support warning level and react render

common/config/rush/pnpm-lock.yaml, packages/plugins/background-plugin/src/background-layer.tsx, packages/plugins/background-plugin/src/create-background-plugin.ts, packages/plugins/free-container-plugin/package.json, packages/plugins/free-container-plugin/src/sub-canvas/components/background/index.tsx, packages/plugins/free-container-plugin/src/sub-canvas/components/background/style.ts
此PR添加了子画布背景支持，子画布现在可以自动继承主画布背景插件的配置。
- **子画布背景同步**: 子画布现在使用与主画布相同的背景配置
- **Inversify 依赖注入**: 使用 `useService` 从 IoC 容器获取 `BackgroundConfig`
- **优雅回退**: 当背景插件未注册时，回退到默认值
- **支持所有背景选项**: backgroundColor、dotColor、dotSize、gridSize、dotOpacity、dotFillColor
- 修改 `SubCanvasBackground` 组件使用依赖注入
- 为 `free-container-plugin` 添加 `@flowgram.ai/background-plugin` 依赖
- 更新背景插件以导出并绑定 `BackgroundConfig` 符号  
- 移除硬编码的背景样式，改为动态配置
- ✅ 所有测试通过 (`npm test`)
- ✅ 代码风格检查通过 (`rush lint`)
- ✅ 构建验证通过 (`rush build`)
- ✅ 使用演示配置测试功能
无需额外配置。当用户在编辑器属性中设置背景时：
```tsx
const editorProps = {
background: {
backgroundColor: '#1a1a1a',
dotColor: '#ffffff', 
dotSize: 1,
gridSize: 20,
dotOpacity: 0.3,
logo: {
text: '您的品牌',
position: 'center',
size: 200,
opacity: 0.25,
color: '#ffffff',
neumorphism: {
enabled: true,
textColor: …
```
=> feat(free-container-plugin): 添加子画布背景支持，使用inversify依赖注入

packages/client/free-layout-editor/src/hooks/use-auto-layout.ts, packages/client/free-layout-editor/src/hooks/use-playground-tools.ts, packages/plugins/free-auto-layout-plugin/src/layout/type.ts
await tools.autoLayout({
disableFitView: true,
});
```ts
export const AutoLayout = () => {
const tools = usePlaygroundTools();
const playground = usePlayground();
const autoLayout = useCallback(async () => {
await tools.autoLayout({
disableFitView: true,
});
}, [tools]);
return (
<Tooltip content={'Auto Layout'}>
<IconButton
disabled={playground.config.readonly}
type="tertiary"
theme="borderless"
onClick={autoLayout}
icon={IconAutoLayout}
/>
</Tooltip>
);
};
```
=> feat(client): autoLayout add disableFitView option

apps/docs/global.less
=> style(docs): Change fixed width to adaptive width.

apps/demo-free-layout/package.json, common/config/rush/pnpm-lock.yaml, packages/materials/form-materials/package.json
Before optimization:
And a lot of shiki packages
After optimization:
=> chore(material): optimize coze-editor bundle size

apps/demo-fixed-layout-simple/src/components/minimap.tsx, apps/demo-fixed-layout-simple/src/hooks/use-editor-props.tsx, apps/demo-fixed-layout/src/components/node-adder/styles.tsx, apps/demo-fixed-layout/src/components/tools/minimap.tsx, apps/demo-fixed-layout/src/hooks/use-editor-props.ts, apps/demo-free-layout-simple/src/components/minimap.tsx, apps/demo-free-layout-simple/src/hooks/use-editor-props.tsx, apps/demo-free-layout/src/components/tools/minimap.tsx, apps/demo-free-layout/src/hooks/use-editor-props.tsx, apps/demo-nextjs-antd/src/editor/hooks/use-editor-props.tsx, apps/demo-nextjs/src/editor/hooks/use-editor-props.tsx, apps/demo-node-form/src/hooks/use-editor-props.tsx, apps/demo-react-16/src/components/minimap.tsx, apps/demo-react-16/src/hooks/use-editor-props.tsx, apps/demo-vite/src/components/minimap.tsx, apps/demo-vite/src/hooks/use-editor-props.tsx, apps/docs/src/en/examples/free-layout/free-layout-simple.mdx, apps/docs/src/en/guide/advanced/minimap.mdx, apps/docs/src/zh/examples/free-layout/free-layout-simple.mdx, apps/docs/src/zh/guide/advanced/minimap.mdx, packages/plugins/minimap-plugin/src/component.tsx, packages/plugins/minimap-plugin/src/constant.ts, packages/plugins/minimap-plugin/src/layer.tsx, packages/plugins/minimap-plugin/src/service.ts, packages/plugins/minimap-plugin/src/type.ts
1. throttle 替代 debounce，去掉 enableInactiveDebounce 和 enableActiveDebounce， inactiveDebounce -> inactiveThrottle, activeDebounce -> activeThrottle
2. 不要使用 entityManager.onChange 改成用 observeEntityDatas(FlowNodeEntity, TransformData)
3. 添加 setVisible，保证如果 缩略图不渲染不用计算 canvas
4. 默认值 inactiveThrottle 设置为 24 帧，眼睛不会感觉抖动
=> refactor(minimap-plugin): use throttle to improve the performance of minimap, api inactiveDebounceTime -> inactiveThrottleTime

packages/materials/form-materials/src/components/code-editor/theme/dark.ts, packages/materials/form-materials/src/components/code-editor/theme/light.ts
Fixes: https://github.com/bytedance/flowgram.ai/issues/872
=> fix: coze-editor line highlight transparent

apps/docs/src/en/guide/advanced/free-layout/load.mdx, apps/docs/src/zh/guide/advanced/free-layout/load.mdx, packages/canvas-engine/free-layout-core/src/workflow-document.ts, packages/client/free-layout-editor/src/components/free-layout-editor-provider.tsx, packages/client/free-layout-editor/src/preset/free-layout-props.ts
ctx.operation supports diff loading of canvas data and undo operation.
```tsx pure
import { FreeLayoutEditorProvider, FreeLayoutPluginContext, EditorRenderer } from '@flowgram.ai/free-layout-editor'
function App({ data }) {
const ref = useRef<FreeLayoutPluginContext | undefined>();
useEffect(() => {
ref.current.operation.fromJSON(data)
setTimeout(() => {
ref.current.document.fitView()
}, 100)
}, [data])
return (
<FreeLayoutEditorProvider ref={ref} {...otherProps}>
<EditorRenderer className="demo-editor" />
</FreeLayoutEditorProvider>
)
}
```
=> feat(free-layout-editor): add operation(WorkflowOperationService) to FreeLayoutPluginContext
