- apps/demo-fixed-layout/src/plugins/sync-variable-plugin/utils.ts
- apps/demo-fixed-layout/src/plugins/sync-variable-plugin/variable-selector/use-variable-tree.ts
- apps/demo-free-layout/src/plugins/sync-variable-plugin/utils.ts
- apps/demo-free-layout/src/plugins/sync-variable-plugin/variable-selector/use-variable-tree.ts
- packages/variable-engine/variable-core/__tests__/ast/variable-type-equal.test.ts
- packages/variable-engine/variable-core/src/ast/ast-registers.ts
- packages/variable-engine/variable-core/src/ast/factory.ts
- packages/variable-engine/variable-core/src/ast/type/custom-type.ts
- packages/variable-engine/variable-core/src/ast/type/index.ts
- packages/variable-engine/variable-core/src/ast/types.ts
```typescript
ASTFactory.createCustomType({
typeName: 'Custom',
})
```
> feat(variable): add new variable AST CustomType

- apps/docs/src/en/guide/introduction.mdx
> fix(style): text visibility issue in english i18n

- packages/node-engine/node/src/form-model-v2.ts
- packages/node-engine/node/src/types.ts
- fix defaultValues function types
- fix defaultValues function missing context param
> fix: typo & defaultValues func context missing

- apps/docs/src/en/api/core/flow-node-entity.mdx
- apps/docs/src/en/api/core/workflow-document.mdx
- apps/docs/src/en/api/services/command-service.mdx
- apps/docs/src/en/guide/advanced/lines.mdx
- apps/docs/src/zh/api/core/flow-node-entity.mdx
- apps/docs/src/zh/api/core/workflow-document.mdx
- apps/docs/src/zh/api/services/command-service.mdx
- apps/docs/src/zh/guide/advanced/lines.mdx
> fix: link jump 404

- apps/docs/src/en/guide/getting-started/create-free-layout-simple.mdx
- apps/docs/src/zh/guide/getting-started/create-free-layout-simple.mdx
> docs: Modify the FixedLayoutProps in a free layout

- apps/docs/src/en/guide/getting-started/create-fixed-layout-simple.mdx
- apps/docs/src/en/guide/getting-started/create-free-layout-simple.mdx
- apps/docs/src/zh/guide/getting-started/create-fixed-layout-simple.mdx
- apps/docs/src/zh/guide/getting-started/create-free-layout-simple.mdx
- packages/canvas-engine/free-layout-core/src/service/workflow-drag-service.ts
- feat: free-layout support multi inputs
- docs: update guide
> feat: free-layout support multi inputs

- apps/docs/components/index.ts
- apps/docs/components/node-form/dynamic/node-registry.tsx
- apps/docs/components/node-form/dynamic/preview.tsx
- apps/docs/components/node-form/index.ts
- apps/docs/src/zh/examples/node-form/_meta.json
- apps/docs/src/zh/examples/node-form/basic.mdx
- apps/docs/src/zh/examples/node-form/dynamic.mdx
- apps/docs/src/zh/guide/advanced/form.mdx
Improved following docs and add visibility example
> docs: improve node form docs and examples

- apps/demo-fixed-layout-simple/package.json
- apps/demo-fixed-layout/package.json
- apps/demo-free-layout-simple/package.json
- apps/demo-free-layout/package.json
- apps/demo-node-form/package.json
- common/config/rush/pnpm-lock.yaml
> chore: fix scripts with windows

- apps/docs/components/node-form/effect/node-registry.tsx
- apps/docs/components/node-form/effect/preview.tsx
- apps/docs/src/en/examples/_meta.json
- apps/docs/src/en/examples/node-form/_meta.json
- apps/docs/src/en/examples/node-form/array.mdx
- apps/docs/src/en/examples/node-form/basic.mdx
- apps/docs/src/en/examples/node-form/dynamic.mdx
- apps/docs/src/en/examples/node-form/effect.mdx
- apps/docs/src/en/guide/advanced/form.mdx
- apps/docs/src/zh/examples/node-form/array.mdx
- apps/docs/src/zh/examples/node-form/effect.mdx
- apps/docs/src/zh/guide/advanced/form.mdx
1. Add hooks in node form docs
2. improve docs in general
3. add english version
> docs: improve node form docs and add english version for both guide and examples

- apps/demo-free-layout/src/form-components/form-header/index.tsx
- apps/demo-free-layout/src/shortcuts/shortcuts.ts
> fix(demo): Free layout shortcuts copy

- apps/demo-fixed-layout/src/nodes/end/index.ts
- packages/canvas-engine/document/src/typings/flow.ts
> fix: branch end check, all branches are not allowed to be end

- apps/demo-fixed-layout/src/hooks/use-editor-props.ts
- apps/demo-fixed-layout/src/initial-data.ts
- apps/demo-fixed-layout/src/nodes/block/form-meta.tsx
- apps/demo-fixed-layout/src/nodes/block/index.ts
- apps/demo-fixed-layout/src/nodes/condition/index.ts
- apps/demo-fixed-layout/src/nodes/index.ts
- apps/demo-fixed-layout/src/nodes/llm/index.ts
- apps/demo-fixed-layout/src/nodes/loop/index.ts
- apps/demo-fixed-layout/src/nodes/trycatch/form-meta.tsx
- apps/demo-fixed-layout/src/nodes/trycatch/index.ts
> fix(demo): fixed-layout demo block validate

- apps/demo-free-layout/src/nodes/condition/index.ts
- apps/demo-free-layout/src/nodes/constants.ts
- apps/demo-free-layout/src/nodes/end/index.ts
- apps/demo-free-layout/src/nodes/index.ts
- apps/demo-free-layout/src/nodes/llm/index.ts
- apps/demo-free-layout/src/nodes/loop/index.ts
- apps/demo-free-layout/src/nodes/start/index.ts
- apps/demo-free-layout/src/shortcuts/collapse/index.ts
- apps/demo-free-layout/src/shortcuts/constants.ts
- apps/demo-free-layout/src/shortcuts/copy/index.ts
- apps/demo-free-layout/src/shortcuts/delete/index.ts
- apps/demo-free-layout/src/shortcuts/expand/index.ts
- apps/demo-free-layout/src/shortcuts/paste/index.ts
- apps/demo-free-layout/src/shortcuts/paste/traverse.ts
- apps/demo-free-layout/src/shortcuts/paste/unique-workflow.ts
- apps/demo-free-layout/src/shortcuts/select-all/index.ts
- apps/demo-free-layout/src/shortcuts/shortcuts.ts
- apps/demo-free-layout/src/shortcuts/type.ts
- apps/demo-free-layout/src/shortcuts/zoom-in/index.ts
- apps/demo-free-layout/src/shortcuts/zoom-out/index.ts
- cspell.json
- packages/canvas-engine/core/src/common/entity.ts
- packages/canvas-engine/core/src/services/selection-service.ts
- packages/canvas-engine/free-layout-core/src/entity-datas/workflow-node-lines-data.ts
- packages/canvas-engine/free-layout-core/src/service/workflow-drag-service.ts
- packages/canvas-engine/free-layout-core/src/workflow-document.ts
- packages/plugins/free-history-plugin/src/changes/add-node-change.ts
- packages/plugins/free-history-plugin/src/changes/delete-node-change.ts
- packages/plugins/shortcuts-plugin/src/shortcuts-contribution.ts
> feat(free-demo): enhance copy and paste shortcut capabilities

- apps/demo-fixed-layout/src/form-components/form-header/index.tsx
- apps/demo-fixed-layout/src/nodes/block/index.ts
- apps/demo-fixed-layout/src/nodes/end/index.ts
> fix(demo): fixed layout demo node delete check

- apps/demo-free-layout/src/shortcuts/copy/index.ts
- apps/demo-free-layout/src/shortcuts/paste/index.ts
> fix(demo-free): create copy error

- packages/plugins/variable-plugin/src/create-variable-plugin.ts
- packages/plugins/variable-plugin/src/index.ts
- packages/variable-engine/variable-core/src/scope/scope.ts
- packages/variable-engine/variable-core/src/variable-engine.ts
- packages/variable-engine/variable-layout/__mocks__/container.ts
- packages/variable-engine/variable-layout/__mocks__/run-fixed-layout-test.ts
- packages/variable-engine/variable-layout/__mocks__/run-free-layout-test.ts
- packages/variable-engine/variable-layout/__tests__/__snapshots__/variable-fix-enable-global-scope.test.ts.snap
- packages/variable-engine/variable-layout/__tests__/__snapshots__/variable-fix-layout-filter-start-end.test.ts.snap
- packages/variable-engine/variable-layout/__tests__/__snapshots__/variable-fix-layout-group.test.ts.snap
- packages/variable-engine/variable-layout/__tests__/__snapshots__/variable-fix-layout-no-config.test.ts.snap
- packages/variable-engine/variable-layout/__tests__/__snapshots__/variable-free-enable-global-scope.test.ts.snap
- packages/variable-engine/variable-layout/__tests__/__snapshots__/variable-free-layout-transform-empty.test.ts.snap
- packages/variable-engine/variable-layout/__tests__/variable-fix-enable-global-scope.test.ts
- packages/variable-engine/variable-layout/__tests__/variable-free-enable-global-scope.test.ts
- packages/variable-engine/variable-layout/src/chains/fixed-layout-scope-chain.ts
- packages/variable-engine/variable-layout/src/chains/free-layout-scope-chain.ts
- packages/variable-engine/variable-layout/src/index.ts
- packages/variable-engine/variable-layout/src/scopes/global-scope.ts
Example
```typescript
export const createSyncGlobalVariablePlugin: PluginCreator<SyncVariablePluginOptions> =
definePluginCreator<SyncVariablePluginOptions, FixedLayoutPluginContext>({
onInit(ctx, options) {
ctx.get(GlobalScope).setVar(
ASTFactory.createVariableDeclaration({
key: 'GlobalScope',
type: ASTFactory.createObject({}),
meta: {
title: 'GlobalScope',
description: 'GlobalScope',
type: 'string',
},
})
);
},
});
```
> feat(variable): global variable scope

- packages/canvas-engine/renderer/src/layers/flow-nodes-transform-layer.tsx
> perf(layer): browser coord precision causing repeated coord updates

- apps/docs/package.json
- apps/docs/scripts/translate.ts
- apps/docs/tsconfig.json
- common/config/rush/pnpm-lock.yaml
How to use it:
- cd apps/docs
- Add apps/docs/.env file, to set OPENAI_API_KEY, OPENAI_BASE_URL, OPENAI_MODEL
- Use `git add .` to add all changed docs to git staged changes
- Run `npm run translate:zh` to translate all zh files to en
> feat(docs): add auto translate scripts for docs

- apps/demo-fixed-layout/src/components/tools/index.tsx
- apps/demo-fixed-layout/src/components/tools/run.tsx
- apps/demo-free-layout/src/components/tools/index.tsx
- apps/demo-free-layout/src/components/tools/run.tsx
- apps/demo-free-layout/src/hooks/use-editor-props.tsx
- apps/demo-free-layout/src/services/index.ts
- apps/demo-free-layout/src/services/running-service.ts
- apps/demo-free-layout/src/styles/index.css
- packages/canvas-engine/core/src/react-hooks/use-service.ts
- packages/canvas-engine/document/src/typings/flow-transition.ts
- packages/canvas-engine/renderer/__tests__/layers/__snapshots__/flow-label-layer.test.tsx.snap
- packages/canvas-engine/renderer/src/components/CustomLine.tsx
- packages/canvas-engine/renderer/src/components/LabelsRenderer.tsx
- packages/canvas-engine/renderer/src/components/LinesRenderer.tsx
- packages/canvas-engine/renderer/src/components/MarkerActivatedArrow.tsx
- packages/canvas-engine/renderer/src/components/MarkerArrow.tsx
- packages/canvas-engine/renderer/src/components/RoundedTurningLine.tsx
- packages/canvas-engine/renderer/src/components/StraightLine.tsx
- packages/canvas-engine/renderer/src/layers/flow-lines-layer.tsx
- packages/materials/fixed-semi-materials/src/components/try-catch-collapse.tsx
> feat(demo): workflow running style support

- packages/materials/form-materials/bin/index.js
- packages/materials/form-materials/src/components/json-schema-editor/hooks.tsx
- packages/materials/form-materials/src/components/json-schema-editor/index.tsx
https://github.com/user-attachments/assets/cbd0aee5-3479-4803-827f-d78cb767e4fe
> fix(material): json schema editor controlled by value

- packages/canvas-engine/document/src/typings/flow.ts
- packages/canvas-engine/fixed-layout-core/src/activities/index.ts
- packages/canvas-engine/fixed-layout-core/src/activities/simple-split.ts
- packages/canvas-engine/fixed-layout-core/src/flow-registers.ts
- packages/client/fixed-layout-editor/index.css
> feat(fixed-layout): add simple-split node

- apps/demo-fixed-layout/src/nodes/trycatch/index.ts
https://github.com/bytedance/flowgram.ai/issues/230
> fix(demo): fixedlayout trycatch add error

- apps/demo-fixed-layout-simple/src/data/dynamicSplit.ts
- apps/demo-fixed-layout-simple/src/data/index.ts
- apps/demo-fixed-layout-simple/src/data/loop.ts
- apps/demo-fixed-layout-simple/src/data/mindmap.ts
- apps/demo-fixed-layout-simple/src/data/multiInputs.ts
- apps/demo-fixed-layout-simple/src/data/multiOutputs.ts
- apps/demo-fixed-layout-simple/src/data/tryCatch.ts
- apps/demo-fixed-layout-simple/src/editor.tsx
- apps/demo-fixed-layout-simple/src/hooks/use-editor-props.tsx
- apps/docs/components/fixed-layout-simple/composite-nodes-preview.tsx
- apps/docs/components/fixed-layout-simple/fixed-layout-simple.tsx
- apps/docs/components/fixed-layout-simple/index.tsx
- apps/docs/components/free-layout-simple/preview.tsx
- apps/docs/components/index.ts
- apps/docs/components/preview-editor.tsx
- apps/docs/src/en/examples/fixed-layout/_meta.json
- apps/docs/src/en/examples/fixed-layout/fixed-composite-nodes.mdx
- apps/docs/src/en/guide/advanced/fixed-layout/_meta.json
- apps/docs/src/en/guide/advanced/fixed-layout/composite-nodes.mdx
- apps/docs/src/zh/examples/fixed-layout/_meta.json
- apps/docs/src/zh/examples/fixed-layout/fixed-composite-nodes.mdx
- apps/docs/src/zh/guide/advanced/fixed-layout/_meta.json
- apps/docs/src/zh/guide/advanced/fixed-layout/composite-nodes.mdx
> feat(docs): composite nodes docs

- apps/demo-fixed-layout-simple/src/hooks/use-editor-props.tsx
- apps/demo-fixed-layout/src/hooks/use-editor-props.ts
- apps/docs/src/en/guide/getting-started/create-fixed-layout-simple.mdx
- apps/docs/src/zh/guide/getting-started/create-fixed-layout-simple.mdx
- packages/plugins/materials-plugin/src/create-materials-plugin.ts
https://github.com/bytedance/flowgram.ai/issues/283
> feat: add materials.components api

- apps/demo-fixed-layout/src/form-components/form-header/index.tsx
- apps/demo-fixed-layout/src/form-components/form-header/title-input.tsx
- apps/demo-free-layout/src/components/node-menu/index.tsx
- apps/demo-free-layout/src/form-components/form-header/index.tsx
- apps/demo-free-layout/src/form-components/form-header/title-input.tsx
> feat(demo): node title editable

- packages/common/utils/src/disposable.spec.ts
- packages/common/utils/src/disposable.ts
```typescript
const dc1 = new DisposableCollection();
const disposable1: Disposable = {
dispose() {},
};
dc1.push(disposable1);
disposable1.dispose()
expect(dc1.length).toEqual(0); // dc1 需要自动清空不然会造成内存泄漏
```
> feat(utils): DisposableCollection auto remove

- apps/docs/src/en/guide/advanced/fixed-layout/node.mdx
- apps/docs/src/en/guide/advanced/free-layout/node.mdx
- apps/docs/src/zh/guide/advanced/fixed-layout/node.mdx
- apps/docs/src/zh/guide/advanced/free-layout/node.mdx
- packages/canvas-engine/free-layout-core/src/hooks/typings.ts
- packages/canvas-engine/free-layout-core/src/hooks/use-node-render.tsx
- packages/client/fixed-layout-editor/src/hooks/use-node-render.tsx
```typescript
function BaseNode() {
const { id, type, data, updateData } = useNodeRender();
// 对应节点的 data 数据
console.log(data)
function onChange(e) {
updateData({
...data,
title: e.target.value
})
}
return <input value={data.title} onChange={onChange}/>
}
```
> feat: use-node-render add id、type、data、updateData

- README.md
- packages/plugins/free-group-plugin/src/create-free-group-plugin.tsx
- packages/plugins/free-group-plugin/src/type.ts
- packages/plugins/free-group-plugin/src/workflow-group-service.ts
> feat(free-group-plugin): add initGroupJSON config

- CONTRIBUTING.md
- README.md
`docs(readme): optimize command and version for Rush setup`  
This PR updates the `README.md` to align with Rush best practices and improve installation efficiency:  
1. **Command Optimization**  
- Replaced `rush update` with `rush install` in the setup instructions.  
- **Reason**: `rush install` uses the existing `shrinkwrap` file for deterministic installations, reducing dependency resolution time and ensuring consistency across environments.  
- *Impact*: Faster setup for new contributors and reduced risk of dependency conflicts.  
2. **Version Synchronization**  
- Updated the global Rush installation command from `@microsoft/rush@5.140.0` to `@microsoft/rush@5.140.1`.  
- **Reason**: Matches the version specified in `rush.json` (`5.140.1`), avoiding redundant version resolutions …
> docs(readme): optimize command and version for rush setup

- apps/demo-free-layout/src/components/base-node/node-wrapper.tsx
- apps/demo-free-layout/src/components/node-panel/node-list.tsx
- apps/demo-free-layout/src/components/sidebar/sidebar-renderer.tsx
- apps/demo-free-layout/src/hooks/use-editor-props.tsx
- apps/demo-free-layout/src/initial-data.ts
- apps/demo-free-layout/src/nodes/block-end/form-meta.tsx
- apps/demo-free-layout/src/nodes/block-end/index.ts
- apps/demo-free-layout/src/nodes/block-start/form-meta.tsx
- apps/demo-free-layout/src/nodes/block-start/index.ts
- apps/demo-free-layout/src/nodes/comment/index.tsx
- apps/demo-free-layout/src/nodes/constants.ts
- apps/demo-free-layout/src/nodes/end/index.ts
- apps/demo-free-layout/src/nodes/index.ts
- apps/demo-free-layout/src/nodes/llm/index.ts
- apps/demo-free-layout/src/nodes/loop/create-built-in-nodes.ts
- apps/demo-free-layout/src/nodes/loop/index.ts
- apps/demo-free-layout/src/typings/node.ts
- packages/plugins/free-container-plugin/src/node-into-container/service.ts
> feat(demo): loop built in start & end node

- apps/docs/components/materials.tsx
- packages/materials/form-antd-materials/src/components/condition-row/index.tsx
- packages/materials/form-materials/src/components/condition-row/index.tsx
> fix(materials): mouseup event propagation in condition

- apps/demo-fixed-layout/src/form-components/properties-edit/index.tsx
- apps/demo-free-layout/src/form-components/properties-edit/index.tsx
- apps/demo-nextjs-antd/src/editor/form-components/properties-edit/index.tsx
修复了这个问题 https://github.com/bytedance/flowgram.ai/issues/325
但是修改 demo-nextjs-antd里相应内容后，无法成功执行commit。所以没有提交这个demo里的文件修改。
> fix(demo): 节点内更新属性时保持原有顺序

- apps/demo-fixed-layout/src/components/sidebar/sidebar-node-renderer.tsx
- apps/demo-fixed-layout/src/components/sidebar/sidebar-renderer.tsx
- apps/demo-fixed-layout/src/form-components/form-content/styles.tsx
- apps/demo-fixed-layout/src/form-components/form-header/index.tsx
- apps/demo-fixed-layout/src/form-components/form-header/styles.tsx
- apps/demo-free-layout/src/components/sidebar/sidebar-node-renderer.tsx
- apps/demo-free-layout/src/components/sidebar/sidebar-renderer.tsx
- apps/demo-free-layout/src/form-components/form-content/styles.tsx
- apps/demo-free-layout/src/form-components/form-header/index.tsx
- apps/demo-free-layout/src/form-components/form-header/styles.tsx
> feat(demo): beautify sidebar style

- common/config/rush/pnpm-lock.yaml
- packages/materials/form-materials/package.json
- packages/materials/form-materials/src/components/code-editor/config.json
- packages/materials/form-materials/src/components/json-editor-with-variables/config.json
- packages/materials/form-materials/src/components/prompt-editor-with-inputs/config.json
- packages/materials/form-materials/src/components/prompt-editor-with-variables/config.json
- packages/materials/form-materials/src/components/prompt-editor/config.json
- packages/materials/form-materials/src/components/prompt-editor/index.tsx
- packages/materials/form-materials/src/components/prompt-editor/types.tsx
> feat(material): prompt editor placeholder

- apps/docs/src/en/guide/runtime/_meta.json
- apps/docs/src/en/guide/runtime/api.mdx
- apps/docs/src/en/guide/runtime/introduction.mdx
- apps/docs/src/zh/guide/runtime/_meta.json
- apps/docs/src/zh/guide/runtime/api.mdx
- apps/docs/src/zh/guide/runtime/introduction.mdx
- apps/docs/src/zh/guide/runtime/quick-start.mdx
> feat(docs): runtime api docs

- packages/materials/form-materials/src/components/code-editor/index.tsx
- packages/materials/form-materials/src/components/code-editor/theme/light.ts
- packages/materials/form-materials/src/components/json-editor-with-variables/index.tsx
> fix(material): json-editor-with-variables grammar hint

- apps/demo-fixed-layout-simple/src/components/slot-adder.tsx
- apps/demo-fixed-layout-simple/src/data/index.ts
- apps/demo-fixed-layout-simple/src/data/slot.ts
- apps/demo-fixed-layout-simple/src/data/slots.ts
- apps/demo-fixed-layout-simple/src/hooks/use-editor-props.tsx
- apps/demo-fixed-layout/src/components/agent-adder/index.tsx
- apps/demo-fixed-layout/src/components/index.ts
- apps/demo-fixed-layout/src/hooks/use-editor-props.ts
- apps/demo-fixed-layout/src/nodes/agent/agent-llm.ts
- apps/demo-fixed-layout/src/nodes/agent/agent-memory.ts
- apps/demo-fixed-layout/src/nodes/agent/agent-tools.ts
- apps/docs/components/fixed-layout-simple/composite-nodes-preview.tsx
- packages/canvas-engine/document/__tests__/flow-node-registry.spec.ts
- packages/canvas-engine/document/src/entities/flow-node-entity.ts
- packages/canvas-engine/document/src/flow-document.ts
- packages/canvas-engine/document/src/typings/flow.ts
- packages/canvas-engine/fixed-layout-core/src/activities/slot/constants.ts
- packages/canvas-engine/fixed-layout-core/src/activities/slot/extends/index.ts
- packages/canvas-engine/fixed-layout-core/src/activities/slot/extends/slot-block.ts
- packages/canvas-engine/fixed-layout-core/src/activities/slot/extends/slot-inline-blocks.ts
- packages/canvas-engine/fixed-layout-core/src/activities/slot/index.ts
- packages/canvas-engine/fixed-layout-core/src/activities/slot/typings.ts
- packages/canvas-engine/fixed-layout-core/src/activities/slot/utils/create.ts
- packages/canvas-engine/fixed-layout-core/src/activities/slot/utils/node.ts
- packages/canvas-engine/fixed-layout-core/src/flow-registers.ts
- packages/canvas-engine/renderer/src/flow-renderer-registry.ts
- packages/materials/fixed-semi-materials/src/components/index.tsx
- packages/materials/fixed-semi-materials/src/components/slot-adder.tsx
> feat(fixed-layout): slotPort -> slotBlock

- apps/demo-free-layout/src/components/sidebar/sidebar-renderer.tsx
- apps/demo-free-layout/src/components/testrun/testrun-button/index.tsx
- apps/demo-free-layout/src/components/testrun/testrun-panel/index.module.less
- apps/demo-free-layout/src/components/testrun/testrun-panel/index.tsx
> feat(demo): beautify testrun panel style

- apps/demo-free-layout/src/components/testrun/testrun-form/use-fields.ts
- packages/runtime/js-core/src/domain/validation/index.test.ts
- packages/runtime/js-core/src/domain/validation/index.ts
- packages/runtime/js-core/src/domain/validation/validators/cycle-detection.test.ts
- packages/runtime/js-core/src/domain/validation/validators/cycle-detection.ts
- packages/runtime/js-core/src/domain/validation/validators/edge-source-target-exist.test.ts
- packages/runtime/js-core/src/domain/validation/validators/edge-source-target-exist.ts
- packages/runtime/js-core/src/domain/validation/validators/index.ts
- packages/runtime/js-core/src/domain/validation/validators/schema-format.test.ts
- packages/runtime/js-core/src/domain/validation/validators/schema-format.ts
- packages/runtime/js-core/src/domain/validation/validators/start-end-node.test.ts
- packages/runtime/js-core/src/domain/validation/validators/start-end-node.ts
- packages/runtime/js-core/src/nodes/condition/index.ts
- packages/runtime/js-core/src/nodes/llm/api-validator.ts
- packages/runtime/js-core/src/nodes/llm/index.ts
- packages/runtime/js-core/src/nodes/loop/index.ts
1. Check schema format
1. Check for cycles in the workflow graph
1. Check if edge source and target nodes exist
1. Check if there is only one start node and one end node
> feat(runtime): schema validation

- apps/demo-free-layout/src/components/testrun/node-status-bar/viewer/index.tsx
- packages/runtime/interface/src/node/constant.ts
- packages/runtime/interface/src/node/http/constant.ts
- packages/runtime/interface/src/node/http/index.ts
- packages/runtime/interface/src/node/index.ts
- packages/runtime/interface/src/runtime/executor/node-executor.ts
- packages/runtime/interface/src/runtime/state/index.ts
- packages/runtime/js-core/src/domain/__tests__/schemas/http-real.test.ts
- packages/runtime/js-core/src/domain/__tests__/schemas/http.test.ts
- packages/runtime/js-core/src/domain/__tests__/schemas/http.ts
- packages/runtime/js-core/src/domain/__tests__/schemas/index.ts
- packages/runtime/js-core/src/domain/__tests__/schemas/llm-real.test.ts
- packages/runtime/js-core/src/domain/__tests__/schemas/llm-real.ts
- packages/runtime/js-core/src/domain/engine/index.ts
- packages/runtime/js-core/src/domain/state/index.ts
- packages/runtime/js-core/src/nodes/http/index.ts
- packages/runtime/js-core/src/nodes/index.ts
https://github.com/user-attachments/assets/d0eca1e3-5d25-42bd-8b85-21fef6a2920c
> feat(runtime): http node

- packages/runtime/interface/src/node/break/index.ts
- packages/runtime/interface/src/node/constant.ts
- packages/runtime/interface/src/node/continue/index.ts
- packages/runtime/interface/src/node/index.ts
- packages/runtime/interface/src/runtime/cache/index.ts
- packages/runtime/interface/src/runtime/context/index.ts
- packages/runtime/interface/src/runtime/index.ts
- packages/runtime/js-core/src/domain/__tests__/schemas/index.ts
- packages/runtime/js-core/src/domain/__tests__/schemas/loop-break-continue.test.ts
- packages/runtime/js-core/src/domain/__tests__/schemas/loop-break-continue.ts
- packages/runtime/js-core/src/domain/cache/index.ts
- packages/runtime/js-core/src/domain/context/index.ts
- packages/runtime/js-core/src/domain/engine/index.ts
- packages/runtime/js-core/src/nodes/break/index.ts
- packages/runtime/js-core/src/nodes/condition/index.ts
- packages/runtime/js-core/src/nodes/continue/index.ts
- packages/runtime/js-core/src/nodes/index.ts
- packages/runtime/js-core/src/nodes/loop/index.ts
https://github.com/user-attachments/assets/aea40b05-20f3-4d50-87af-e3e72b42cd0c
> feat(runtime): break & continue node

- apps/demo-free-layout/src/components/sidebar/sidebar-renderer.tsx
- apps/demo-free-layout/src/nodes/code/components/code.tsx
- apps/demo-free-layout/src/nodes/code/components/inputs.tsx
- apps/demo-free-layout/src/nodes/code/components/outputs.tsx
- apps/demo-free-layout/src/nodes/code/form-meta.tsx
- apps/demo-free-layout/src/nodes/code/index.tsx
- apps/demo-free-layout/src/nodes/code/types.tsx
- apps/demo-free-layout/src/nodes/constants.ts
- apps/demo-free-layout/src/nodes/http/components/api.tsx
- apps/demo-free-layout/src/nodes/http/components/body.tsx
- apps/demo-free-layout/src/nodes/http/components/headers.tsx
- apps/demo-free-layout/src/nodes/http/components/timeout.tsx
- apps/demo-free-layout/src/nodes/http/form-meta.tsx
- apps/demo-free-layout/src/nodes/http/index.tsx
- apps/demo-free-layout/src/nodes/index.ts
- apps/demo-free-layout/src/nodes/loop/form-meta.tsx
- apps/demo-free-layout/src/nodes/loop/index.ts
- packages/materials/form-materials/src/components/inputs-values/index.tsx
- packages/materials/form-materials/src/components/json-schema-editor/index.tsx
- packages/materials/form-materials/src/components/prompt-editor-with-inputs/inputs-picker.tsx
> feat(demo): script node

- packages/materials/form-materials/src/components/inputs-values/components/blur-input.tsx
- packages/materials/form-materials/src/components/inputs-values/index.tsx
- packages/materials/form-materials/src/components/inputs-values/types.ts
- packages/materials/form-materials/src/components/prompt-editor-with-variables/extensions/variable-tag.tsx
- packages/materials/form-materials/src/components/variable-selector/index.tsx
- packages/materials/form-materials/src/components/variable-selector/use-variable-tree.tsx
- packages/materials/form-materials/src/hooks/use-object-list/index.tsx
- packages/materials/form-materials/src/typings/flow-value/index.ts
> feat(material): enhance inputs values

- apps/demo-fixed-layout/src/nodes/default-form-meta.tsx
- apps/demo-free-layout/src/nodes/default-form-meta.tsx
- apps/demo-free-layout/src/plugins/context-menu-plugin/context-menu-layer.tsx
- apps/docs/src/en/guide/advanced/form.mdx
- apps/docs/src/zh/guide/advanced/form.mdx
- packages/node-engine/form/__tests__/form-model.test.ts
- packages/node-engine/form/src/core/form-model.ts
- packages/node-engine/form/src/types/form.ts
- packages/node-engine/node/src/types.ts
> feat(form): validate support dynamic function

- apps/demo-free-layout/src/nodes/condition/condition-inputs/index.tsx
- apps/demo-nextjs-antd/src/editor/nodes/condition/condition-inputs/index.tsx
- packages/materials/form-antd-materials/src/components/condition-row/hooks/useOp.tsx
- packages/materials/form-antd-materials/src/components/condition-row/index.tsx
- packages/materials/form-materials/src/components/condition-row/hooks/useOp.tsx
- packages/materials/form-materials/src/components/condition-row/index.tsx
> fix(materials): condition-row readonly support

- common/config/rush/pnpm-lock.yaml
- packages/materials/form-materials/src/components/condition-row/constants.ts
- packages/materials/form-materials/src/components/json-schema-editor/config.json
- packages/materials/form-materials/src/shared/json-schema-preset/create-type-preset-plugin.tsx
- packages/variable-engine/json-schema/src/context.tsx
- packages/variable-engine/variable-core/package.json
> feat(material): add condition rows for array

- apps/demo-free-layout/src/nodes/constants.ts
- apps/demo-free-layout/src/nodes/index.ts
- apps/demo-free-layout/src/nodes/variable/form-meta.tsx
- apps/demo-free-layout/src/nodes/variable/index.tsx
- apps/demo-free-layout/src/nodes/variable/types.tsx
- packages/materials/form-materials/src/components/assign-row/components/blur-input.tsx
- packages/materials/form-materials/src/components/assign-row/config.json
- packages/materials/form-materials/src/components/assign-row/index.tsx
- packages/materials/form-materials/src/components/assign-row/types.ts
- packages/materials/form-materials/src/components/assign-rows/config.json
- packages/materials/form-materials/src/components/assign-rows/index.tsx
- packages/materials/form-materials/src/components/display-outputs/index.tsx
- packages/materials/form-materials/src/components/index.ts
- packages/materials/form-materials/src/components/variable-selector/index.tsx
- packages/materials/form-materials/src/form-plugins/index.ts
- packages/materials/form-materials/src/form-plugins/infer-assign-plugin/config.json
- packages/materials/form-materials/src/form-plugins/infer-assign-plugin/index.ts
> feat(material): variable assign

- packages/materials/form-materials/src/effects/index.ts
- packages/materials/form-materials/src/effects/listen-ref-schema-change/config.json
- packages/materials/form-materials/src/effects/listen-ref-schema-change/index.ts
- packages/materials/form-materials/src/effects/listen-ref-value-change/config.json
- packages/materials/form-materials/src/effects/listen-ref-value-change/index.ts
- packages/node-engine/node/src/form-model-v2.ts
- packages/node-engine/node/src/utils.ts
- packages/variable-engine/variable-core/src/scope/datas/scope-available-data.ts
> feat(material): listen ref change

- apps/demo-free-layout-simple/src/components/node-add-panel.tsx
- apps/demo-free-layout-simple/src/initial-data.ts
- apps/demo-free-layout-simple/src/node-registries.ts
- packages/canvas-engine/free-layout-core/src/entities/workflow-port-entity.ts
- packages/canvas-engine/free-layout-core/src/entity-datas/workflow-node-ports-data.ts
- packages/canvas-engine/free-layout-core/src/typings/workflow-registry.ts
- packages/canvas-engine/free-layout-core/src/workflow-lines-manager.ts
- packages/client/free-layout-editor/src/preset/free-layout-props.ts
> feat(free-layout): workflowPortEntity add location/offset/size

- packages/materials/form-materials/src/components/condition-row/constants.ts
- packages/materials/form-materials/src/components/condition-row/hooks/useOp.tsx
- packages/materials/form-materials/src/components/condition-row/hooks/useRule.ts
- packages/materials/form-materials/src/components/condition-row/index.tsx
- packages/materials/form-materials/src/components/condition-row/types.ts
- packages/materials/form-materials/src/components/json-schema-editor/index.tsx
- packages/materials/form-materials/src/components/type-selector/index.tsx
- packages/materials/form-materials/src/components/variable-selector/index.tsx
- packages/materials/form-materials/src/plugins/json-schema-preset/type-definition/array.tsx
- packages/materials/form-materials/src/plugins/json-schema-preset/type-definition/boolean.tsx
- packages/materials/form-materials/src/plugins/json-schema-preset/type-definition/integer.tsx
- packages/materials/form-materials/src/plugins/json-schema-preset/type-definition/number.tsx
- packages/materials/form-materials/src/plugins/json-schema-preset/type-definition/object.tsx
- packages/materials/form-materials/src/plugins/json-schema-preset/type-definition/string.tsx
> feat(material): form-materials i18n

- apps/demo-free-layout/src/hooks/use-editor-props.tsx
- packages/materials/form-materials/src/components/assign-row/index.tsx
- packages/materials/form-materials/src/components/batch-outputs/index.tsx
- packages/materials/form-materials/src/components/condition-row/index.tsx
- packages/materials/form-materials/src/components/dynamic-value-input/index.tsx
- packages/materials/form-materials/src/components/inputs-values/index.tsx
- packages/materials/form-materials/src/components/json-schema-editor/index.tsx
- packages/materials/form-materials/src/components/type-selector/index.tsx
- packages/materials/form-materials/src/components/variable-selector/index.tsx
- packages/materials/form-materials/src/shared/index.ts
- packages/materials/form-materials/src/shared/inject-material/README.md
- packages/materials/form-materials/src/shared/inject-material/README.zh.md
- packages/materials/form-materials/src/shared/inject-material/index.tsx
> feat(material): inject materials like VariableSelector, TypeSelector

- apps/demo-fixed-layout/src/components/agent-adder/index.tsx
- apps/demo-fixed-layout/src/components/agent-label/index.tsx
- apps/demo-fixed-layout/src/hooks/use-editor-props.ts
- apps/demo-fixed-layout/src/initial-data.ts
- apps/demo-fixed-layout/src/nodes/agent/memory.ts
- apps/demo-fixed-layout/src/nodes/agent/tool.ts
- apps/demo-fixed-layout/src/nodes/loop/form-meta.tsx
- apps/demo-fixed-layout/src/nodes/loop/index.ts
- apps/demo-free-layout/src/nodes/loop/form-meta.tsx
- packages/canvas-engine/document/src/typings/flow-node-register.ts
- packages/canvas-engine/document/src/typings/flow-transition.ts
- packages/canvas-engine/fixed-layout-core/__tests__/__snapshots__/flow-activities.spec.ts.snap
- packages/canvas-engine/fixed-layout-core/src/activities/slot/constants.ts
- packages/canvas-engine/fixed-layout-core/src/activities/slot/extends/slot-block.ts
- packages/canvas-engine/fixed-layout-core/src/activities/slot/extends/slot-inline-blocks.ts
- packages/canvas-engine/fixed-layout-core/src/activities/slot/index.ts
- packages/canvas-engine/fixed-layout-core/src/activities/slot/slot.ts
- packages/canvas-engine/fixed-layout-core/src/activities/slot/utils/transition.ts
- packages/canvas-engine/fixed-layout-core/src/index.ts
- packages/canvas-engine/renderer/src/components/LabelsRenderer.tsx
- packages/canvas-engine/renderer/src/components/RoundedTurningLine.tsx
- packages/canvas-engine/renderer/src/flow-renderer-registry.ts
- packages/materials/fixed-semi-materials/src/components/collapse/index.tsx
- packages/materials/fixed-semi-materials/src/components/index.tsx
- packages/materials/fixed-semi-materials/src/components/slot-collapse.tsx
> feat(fixed-layout): optimize slot ux

- packages/materials/form-materials/src/components/prompt-editor/index.tsx
> feat(material): prompt-editor component expose the options attribute

- apps/demo-free-layout/package.json
- apps/demo-free-layout/src/form-components/form-header/index.tsx
- apps/demo-free-layout/src/nodes/loop/index.ts
- apps/demo-free-layout/src/utils/index.ts
- apps/demo-free-layout/src/utils/toggle-loop-expanded.ts
> feat(free-layout-demo): loop support collapsed

- apps/docs/src/en/guide/advanced/free-layout/line.mdx
- apps/docs/src/en/guide/advanced/free-layout/node.mdx
- apps/docs/src/zh/guide/advanced/free-layout/line.mdx
- apps/docs/src/zh/guide/advanced/free-layout/node.mdx
- packages/canvas-engine/free-layout-core/__tests__/workflow-lines-manager.test.ts
- packages/canvas-engine/free-layout-core/src/entity-datas/workflow-node-lines-data.ts
```typescript
// input lines (contains the line that isDrawing or isHidden)
node.getData(WorkflowNodeLinesData).inputLines
// output lines (contains the line that isDrawing or isHidden)
node.getData(WorkflowNodeLinesData).outputLines
// all availableLines (Doesn't contain the lines that isDrawing or isHidden)
node.getData(WorkflowNodeLinesData).availableLines
```
> feat(free-layout): add availableLines to WorkflowNodeLinesData

- apps/demo-free-layout/src/nodes/group/index.tsx
> fix(demo-free-layout): group node cannot add from node-panel

- apps/demo-free-layout/src/hooks/use-port-click.ts
- apps/demo-free-layout/src/utils/on-drag-line-end.ts
- packages/plugins/free-node-panel-plugin/src/utils/adjust-node-position.ts
- packages/plugins/free-node-panel-plugin/src/utils/build-line.ts
> feat(free-layout): auto create line from bottom port

- apps/demo-free-layout/src/form-components/form-header/index.tsx
- apps/demo-free-layout/src/utils/toggle-loop-expanded.ts
https://github.com/bytedance/flowgram.ai/issues/731
> fix(demo-free-layout): loop collapsed from selector-box

- packages/materials/form-materials/src/components/code-editor-mini/index.tsx
- packages/materials/form-materials/src/components/code-editor/editor.tsx
- packages/materials/form-materials/src/components/code-editor/index.tsx
- packages/materials/form-materials/src/components/json-editor-with-variables/editor.tsx
- packages/materials/form-materials/src/components/json-editor-with-variables/index.tsx
- packages/materials/form-materials/src/components/prompt-editor-with-inputs/editor.tsx
- packages/materials/form-materials/src/components/prompt-editor-with-inputs/index.tsx
- packages/materials/form-materials/src/components/prompt-editor-with-variables/editor.tsx
- packages/materials/form-materials/src/components/prompt-editor-with-variables/index.tsx
- packages/materials/form-materials/src/components/prompt-editor/editor.tsx
- packages/materials/form-materials/src/components/prompt-editor/index.tsx
Before Optimization:
After Optimization:
> chore(material): lazy import editors

- apps/demo-free-layout/src/components/testrun/hooks/use-sync-default.ts
fix(demo-free-layout): test run json mode sync default value (https://github.com/bytedance/flowgram.ai/issues/742)
> fix(demo-free-layout): test run json mode sync default value

- packages/materials/form-materials/src/components/condition-row/constants.ts
- packages/materials/form-materials/src/components/variable-selector/context.tsx
- packages/materials/form-materials/src/components/variable-selector/index.tsx
- packages/materials/form-materials/src/components/variable-selector/use-variable-tree.tsx
- packages/materials/form-materials/src/plugins/json-schema-preset/type-definition/date-time.tsx
- packages/materials/form-materials/src/plugins/json-schema-preset/type-definition/index.tsx
- packages/variable-engine/json-schema/src/json-schema/json-schema-type-manager.tsx
- packages/variable-engine/json-schema/src/json-schema/type-definition/date-time.tsx
- packages/variable-engine/json-schema/src/json-schema/types.ts
- packages/variable-engine/json-schema/src/json-schema/utils.ts
- packages/variable-engine/variable-core/src/ast/factory.ts
- packages/variable-engine/variable-core/src/ast/type/string.ts
> feat(material): skip variable context + datetime support

- README.md
> chore: add juejin tag

- apps/demo-nextjs-antd/.eslintrc.js
- apps/demo-nextjs-antd/package.json
- apps/demo-nextjs-antd/src/editor/components/node-panel/index.tsx
- apps/demo-nextjs/package.json
- common/config/rush/pnpm-lock.yaml
https://github.com/bytedance/flowgram.ai/security/dependabot?q=is%3Aopen+manifest%3Aapps%2Fdemo-nextjs%2Fpackage.json+package%3Anext
> fix: upgrade nodejs for CVE-2025-57822

- CONTRIBUTING.md
- README.md
- apps/docs/src/en/guide/runtime/quick-start.mdx
- apps/docs/src/zh/guide/runtime/quick-start.mdx
- common/autoinstallers/rush-lint-staged/package.json
- common/autoinstallers/rush-lint-staged/pnpm-lock.yaml
- common/config/rush/pnpm-lock.yaml
- common/scripts/install-run.js
- rush.json
fix dep bot error 
- https://github.com/bytedance/flowgram.ai/security/dependabot/69
- https://github.com/bytedance/flowgram.ai/security/dependabot/6
> chore: upgrade rush version

- packages/canvas-engine/free-layout-core/src/utils/get-url-params.ts
Fix https://github.com/bytedance/flowgram.ai/security/code-scanning/8
> fix(core): prototype pollution attack

- README.md
> chore: Update README.md Adoption

- packages/canvas-engine/document/src/flow-document-options.ts
- packages/canvas-engine/document/src/flow-document.ts
- packages/canvas-engine/free-layout-core/src/workflow-document.ts
- packages/client/editor/src/preset/editor-default-preset.ts
> fix(core): flow-document add options.preNodeCreate and fix node.form is undefined when form effect init

- apps/demo-free-layout/src/shortcuts/copy/index.ts
Fixes https://github.com/bytedance/flowgram.ai/issues/732
> fix(demo): group node copy paste

- apps/demo-free-layout/src/nodes/loop/form-meta.tsx
- apps/demo-free-layout/src/nodes/loop/index.ts
> fix(demo): loop node padding

- packages/materials/form-materials/src/components/json-schema-editor/hooks.tsx
> fix(material): json-schema-editor onChange in setState callback

- apps/demo-free-layout/src/components/comment/hooks/use-model.ts
- apps/demo-free-layout/src/components/comment/hooks/use-size.ts
- apps/demo-free-layout/src/hooks/use-editor-props.tsx
- apps/demo-free-layout/src/shortcuts/paste/index.ts
- apps/demo-nextjs-antd/src/editor/shortcuts/paste/index.ts
- packages/canvas-engine/free-layout-core/src/workflow-document.ts
https://github.com/user-attachments/assets/cff376cb-e4d5-4e3b-9732-2d486ddafb61
> feat(document): comment node form update & document create node api optimization

- apps/docs/src/en/guide/advanced/plugin/_meta.json
- apps/docs/src/en/guide/advanced/plugin/free-auto-layout-plugin.mdx
- apps/docs/src/en/guide/advanced/plugin/free-stack-plugin.mdx
- apps/docs/src/en/guide/advanced/plugin/panel-manager-plugin.mdx
- apps/docs/src/zh/guide/advanced/plugin/_meta.json
- apps/docs/src/zh/guide/advanced/plugin/free-stack-plugin.mdx
> docs: free stack plugin

- apps/demo-fixed-layout-simple/src/components/node-add-panel.tsx
- apps/demo-fixed-layout-simple/src/components/node-adder.tsx
- apps/demo-fixed-layout-simple/src/editor.tsx
- apps/demo-fixed-layout-simple/src/hooks/use-add-node.tsx
- apps/demo-fixed-layout-simple/src/hooks/use-editor-props.tsx
- apps/demo-fixed-layout-simple/src/index.css
- apps/demo-fixed-layout/src/components/drag-node/index.tsx
- common/config/rush/pnpm-lock.yaml
- packages/canvas-engine/document/src/entities/flow-renderer-state-entity.ts
- packages/canvas-engine/document/src/services/flow-drag-service.ts
- packages/canvas-engine/renderer/src/layers/flow-drag-layer.tsx
- packages/common/utils/src/types.ts
- packages/materials/fixed-semi-materials/src/components/drag-node/index.tsx
- packages/plugins/fixed-drag-plugin/package.json
- packages/plugins/fixed-drag-plugin/src/create-fixed-drag-plugin.ts
Fixes https://github.com/bytedance/flowgram.ai/issues/859
https://github.com/user-attachments/assets/ce84dcd9-a6ae-4a55-8c7f-25a7dc82facd
> feat: fixed layout supports drag and drop to add nodes

- apps/demo-free-layout/src/nodes/loop/index.ts
- apps/demo-free-layout/src/utils/toggle-loop-expanded.ts
Fixes https://github.com/bytedance/flowgram.ai/issues/873
> fix(demo): empty loop node collapse position offset
